apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-arch-demo

resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- route.yaml
- serviceaccount.yaml
- rolebinding.yaml
